### PR TITLE
Support sections left and right

### PR DESCRIPTION
**Pull request by betaboon**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [x] Docs have been added / updated in README.md (for features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  - feature
  - docs update

* **What is the current behavior?** (You can also link to an open issue here)
  - prompt sections are in fixed order
  - prompt sections can only be disabled
  - prompt sections can only be displayed on the left side

* **What is the new behavior (if this is a feature change)?**
  - prompt section order can be freely configured
  - prompt sections can be displayed on the left and on the right

* **Does this PR introduce a breaking change?** (What changes might users need to make in their configuration due to this PR?)
  - yes. configuration options changed alot again ;)

* **Other information**:
  - i hope I'm not going to far with my PRs XD

alien-left-right

### CODE REVIEW

**Comment by betaboon** [comment]
just found a bug when using sections in `RPROMPT`. 
dont merge yet

**Comment by betaboon** [comment]
ok got the bug sorted out.

**Comment by eendroroy** [comment]
Hi @betaboon,

First of all, THANKS FOR THE AWESOME PULL REQUESTS. Really love those config options.
And **YOU ARE NOT GOING TOO FAR :)**

Regarding this pull request, I originally designed the theme to skip right prompt.
I think it would be great to keep **everything in left prompt by-default**.

**Comment by eendroroy** [comment]
BTW, I also changed a setting and updated README file (hide hostname by default). PR need to be updated.

**Comment by betaboon** [comment]
@eendroroy just got back from vacation.

> Regarding this pull request, I originally designed the theme to skip right prompt.
> I think it would be great to keep **everything in left prompt by-default**.

I will change this PR accordingly.

> BTW, I also changed a setting and updated README file (hide hostname by default). PR need to be updated.

I will do a reverse-merge.

I will do all the changes tomorrow ;)

**Comment by eendroroy** [comment]
@betaboon awesome!

**Comment by betaboon** [comment]
@eendroroy everything should be done accordingly now.

**Comment by eendroroy** [comment]
Merged!

Thanks a lot for your contributions! :)

**Pull request merged**
